hiiiguygy

<?php
    /*    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       $datacollection = $objectManager->get('Magento\Checkout\Model\Session');
       $order=$datacollection->getLastRealOrder();
      // echo "<pre>";print_r($productStockBySku->debug());
       
       
      
        $orderId=$order->getEntityId();
        $a=$order->getIncrementId();
echo $a; */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       $datacollection = $objectManager->get('ISN\CheckBoxEditPage\Model\GridFactory');
      // $order=$datacollection->getLastRealOrder();

        $name=$datacollection ->create();
        $studentobj=$name->load(56);
        $sss= $studentobj->getMagenestcustomcolumn(); 
        echo $sss;
  /*       $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       // $objectManager->get('Magento\Framework\App\State')->setAreaCode('adminhtml'); // adminhtml
    
        // $bootstrap->run($app);
        
        $orderId = 59;
        $order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId( $orderId);
        echo $aa= $order->getOrderId(); */

?>