<?php 
                                 $a= $block->getConfigValue(); 
                                 if($a=='New'){?> 

<img src='<?= $this->getViewFileUrl('ISN_Badge::images/'.$a.'.png'); ?>'style="width: 70.55px;height: 51.6px; position: relative;
top: -369px;z-index: 200;
left: -4px;" alt="image-icon">

                                 <?php } 
                                 elseif($a=='BestSeller'){?> 
 
<img src='<?= $this->getViewFileUrl('ISN_Badge::images/'.$a.'.png'); ?>'style="width: 70.55px;height: 51.6px; position: relative;
top: -369px;z-index: 200;
left: -4px;" alt="image-icon">

<?php } 
                                 elseif($a=='HotDeal'){?> 
 
<img src='<?= $this->getViewFileUrl('ISN_Badge::images/'.$a.'.png'); ?>'style="width: 70.55px;height: 51.6px; position: relative;
top: -369px;z-index: 200;
left: -4px;" alt="image-icon"> ?>
<?php } 
                                 elseif( $a=='Sale'){?> 
 
<img src='<?= $this->getViewFileUrl('ISN_Badge::images/'.$a.'.png'); ?>'style="width: 70.55px;height: 51.6px; position: relative;
top: -369px;z-index: 200;
left: -4px;" alt="image-icon">

<?php }